### ISSUE TITLE
Only part of each tile visible

### ISSUE THREAD

**Issue by camilstaps** [cmfcmf/Anno2018#7]
I'm not sure whether the tiles are clipped (i.e. only part is visible) or scaled (so that the image of the tile is smaller than the tile itself), but on my system each tile contains a lot of black:

![2019-11-26-145446_1916x1039](https://user-images.githubusercontent.com/1202754/69639387-b51f8980-105c-11ea-9c17-4488a6a302ca.png)

This happens to me on both Firefox (68.2.0) and Chromium (76.0.3809.100), on Debian 10.1.

**Comment by cmfcmf** [comment]
Huh, that's an interesting issue I haven't seen before. I am not sure what causes that. Could you verify some things for me?
- What Anno 1602 version are you using (i.e., the GOG edition, a version from an original CD, ...)?
- No idea if this is relevant, but what graphics card are you using?
- Are you able to use the mousewheel to zoom into the map (you should)? Could you zoom into one tile really close and take another screenshot?
- Please use the "Download files" button down the page under the "Downloading all uploaded and converted files" heading to download the converted files (this takes a minute or two and will not display any progress while the zip file is generated. Be patient, your browser will download a zip archive with all uploaded and converted files when it is ready). In the downloaded zip file, open gfx/STADTFLD/sprite-sheet-0.png. It should be a 2048x2048 PNG file. Please verify that there are 32 graphics in the first row.

**Comment by cmfcmf** [comment]
Nevermind that, I think I found and fixed the problem in https://github.com/cmfcmf/Anno2018/commit/5408480ba980faf06e49e7e7f4d998dddf7ab76d. When processing the uploaded zip file, the upload handler looks for a file with the name `GFX/STADTFLD.BSH` using a case insensitive regex. Due to an error on my part, the regex also matched the incorrect `SGFX/STADTFLD.BSH` and `MGFX/STADTFLD.BSH` files. The code uses the first match it finds, and that was always `GFX/STADTFLD.BSH` for me. Your zip file seems to be packed in a different order, which is why it matched `SGFX/STADTFLD.BSH` or `MGFX/STADTFLD.BSH` for you. These contain the smaller versions of the graphics that Anno uses when you are zoomed out the farthest. 

The fix is now live. You'll have to use the "Reset all files" button and then re-upload your Anno zip file. Then it should work!

**Comment by camilstaps** [comment]
Yep, works, thanks! We probably have different zip versions, then. Exciting to see this really working :)
