### ISSUE TITLE
How to set up local instance?

### ISSUE THREAD

**Issue by codeclem** [cmfcmf/Anno2018#9]
I'm trying to run a local instance of the app. I cloned the repo and ran `npm install`, then `npm start`. When uploading my zip it fails when it gets to the WAV files:

```
ERROR: The upload failed.
ERROR: wavefile__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor
INFO: Converting song Emotion.wav
```
This doesn't happen on the live server at christianflach.de so I'm guessing there must be an additional step to installing dependencies.

**Comment by cmfcmf** [comment]
Thank you for bringing this to my attention!
I added a contributing guide in https://github.com/cmfcmf/Anno2018/commit/1e906cef4d06ec955cf6479cf50d72426200a04c. The issue you are facing is likely caused by using `npm`, whereas this repository uses `yarn`. Could you try using `yarn` as written in the guide and see if it works?
In general, there are no special steps taken for the live version. It is deployed using [this GitHub Actions workflow](https://github.com/cmfcmf/Anno2018/blob/master/.github/workflows/main.yml) which basically executes `yarn install && yarn build`.

**Comment by codeclem** [comment]
That fixed the issue. Thanks for adding this to the docs :)
